### /

GET http://localhost:8080 HTTP/1.1

### /users

GET http://localhost:8080/users HTTP/1.1

### /users

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
  "username": "matheus",
  "email": "matheus@example.com",
  "password": "segredo"
}

### /users

PUT http://localhost:8080/users/1 HTTP/1.1
content-type: application/json

{
  "username": "gabriel",
  "email": "gabriel@example.com",
  "password": "segredo"
}

### /users

DELETE http://localhost:8080/users/1 HTTP/1.1
